### ISSUE TITLE
Feat: Plugins

### ISSUE THREAD

**Issue by droans** [droans/klipper_extras#8]
Allow plugins to be created. Plugins would have their own definition in the config yaml. They would act similarly to functions but would receive the configuration from the file.

Example:

```
plugins:
  hass:
    plugin: homeassistant
    config:
      url: https://my.hass.com
      api: XXXXXXXX
      port: 443
      ssl: true
```

Object would be generated at startup and added to the environment for users.
